//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace telefonRehberi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class calisanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public calisanlar()
        {
            this.calisanlar1 = new HashSet<calisanlar>();
        }

        public int id { get; set; }
        public string ad { get; set; }

        public string soyad { get; set; }
        public string tel { get; set; }
        public int departmanId { get; set; }
        public Nullable<int> yoneticiId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calisanlar> calisanlar1 { get; set; }
        public virtual calisanlar calisanlar2 { get; set; }
        public virtual departman departman { get; set; }
    }
}
